// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.Output;

/************************************************************/

public abstract class CorrectResponse implements java.lang.Comparable<CorrectResponse>, java.io.Serializable {

    private static final long serialVersionUID = 8344575018669603214L;

    public CorrectResponse() {
    }

    public int compareTo(SurveyApp.CorrectResponse other) {
	return 0;
    }

    public void display(Output output) {
    }
};
