// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

/************************************************************/
/**
 * 
 */
public class MenuChoice {
    /**
     * 
     */
    private String value;
    /**
     * 
     */
    private int index;

    /**
     * 
     */
    public MenuChoice() {
	this.value = null;
	this.index = 0;
    }

    public MenuChoice(String value, int index) {
	this.value = value;
	this.index = index;
    }

    /**
     * 
     * @param value
     * @return
     */
    public void setValue(String value) {
	this.value = value;
    }

    /**
     * 
     * @param index
     * @return
     */
    public void setIndex(int index) {
	this.index = index;
    }

    /**
     * 
     * @return
     */
    public String getValue() {
	return this.value;
    }

    /**
     * 
     * @return
     */
    public int getIndex() {
	return this.index;
    }
};
