// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

/************************************************************/
/**
 * 
 */
public abstract class Output {
    /**
     * 
     */
    public Output() {
    }

    public void displayInteger(int output) {
	System.out.print(output);
    }

    /**
     * 
     * @param output
     * @return
     */
    public void displayString(String output) {
	System.out.print(output);
    }

};
