// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.CorrectResponse;

/************************************************************/
/**
 * 
 */
public class CorrectResponseInteger extends CorrectResponse {
    /**
     * 
     */
    private static final long serialVersionUID = -2741230783720150495L;
    /**
     * 
     */
    private int response;

    /**
     * 
     */
    public CorrectResponseInteger() {
    }

    public CorrectResponseInteger(int response) {
	this.response = response;
    }

    /**
     * 
     * @return
     */
    public int getResponse() {
	return this.response;
    }

    /**
     * 
     * @param other
     * @return
     */
    public int compareTo(CorrectResponseInteger other) {
	Integer thisValue = new Integer(this.response);

	return thisValue.compareTo(other.response);
    }

    /**
     * 
     * @param response
     * @return
     */
    public void setResponse(int response) {
	this.response = response;
    }
};
