// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.CorrectResponse;

/************************************************************/
/**
 * 
 */
public class CorrectResponseBoolean extends CorrectResponse {
	/**
	 * 
	 */
	public boolean response;

	/**
	 * 
	 * @param response 
	 * @return 
	 */
	public void setResponse(boolean response) {
		this.response = response;
	}

	/**
	 * 
	 */
	public CorrectResponseBoolean() {
	}
	
	public CorrectResponseBoolean(boolean response) {
		this.response = response;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean getResponse() {
		return this.response;
	}

	/**
	 * 
	 * @param other 
	 * @return 
	 */
	public int compareTo(CorrectResponseBoolean other) {
		Boolean thisValue = new Boolean(this.response);
		
		return thisValue.compareTo(other.response);
	}
};
