// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.CorrectResponse;

/************************************************************/
/**
 * 
 */
public class CorrectResponseString extends CorrectResponse {
	/**
	 * 
	 */
	private String response;

	/**
	 * 
	 */
	public CorrectResponseString() {
	}
	
	public CorrectResponseString(String response) {
		this.response = response;
	}

	/**
	 * 
	 * @return 
	 */
	public String getResponse() {
		return this.response;
	}

	/**
	 * 
	 * @param response 
	 * @return 
	 */
	public void setResponse(String response) {
		this.response = response;
	}

	/**
	 * 
	 * @param other 
	 * @return 
	 */
	public int compareTo(CorrectResponseString other) {
		String thisValue = new String(this.response);
		
		return thisValue.compareTo(other.response);
	}
};
