// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.MenuManager;
import SurveyApp.SurveyManager;

/************************************************************/
/**
 * 
 */
public class Main {
	/**
	 * 
	 */
	private SurveyManager surveyManager;
	/**
	 * 
	 */
	private MenuManager menuManager;

	/**
	 * 
	 * @param args 
	 * @return 
	 */
	public void main(SurveyApp.String [] args) {
	}
};
