// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

//import java.util.*;
import SurveyApp.MenuManager;
import SurveyApp.SurveyManager;
//import SurveyApp.*;

/************************************************************/
/**
 * 
 */
public class Main {
    /* Header divider is (80 * '~') */
    public static String DIVIDER_HEADER = "~~~~~~~~~~~~~~~~~~~~" + "~~~~~~~~~~~~~~~~~~~~" + "~~~~~~~~~~~~~~~~~~~~"
	    + "~~~~~~~~~~~~~~~~~~~~";

//	/* Divider is (80 * '=') */
//	public static String DIVIDER = "===================="
//			+ "====================" + "===================="
//			+ "====================";

    public static String APPLICATION_TITLE = "Survey and Test Utility v0.15";
    public static String AUTHOR_NAME = "William J. Anderson";

    public static void printHeaderDivider() {
	System.out.println(DIVIDER_HEADER);
    }

    public static void printHeader() {
	printHeaderDivider();
	System.out.println("\t\t\t" + APPLICATION_TITLE);
	System.out.println("\t\t\tBy: " + AUTHOR_NAME);
	printHeaderDivider();
    }

    @SuppressWarnings("unused")
    private static SurveyManager surveyManager;

    @SuppressWarnings("unused")
    private static MenuManager menuManager;

    /**
     * 
     * @param args
     * @return
     */
    public static void main(String[] args) {
	printHeader();

//		Output mainOutput = OutputTerminal.getInstance();
	menuManager = MenuManager.getInstance();
	surveyManager = SurveyManager.getInstance();
    }
};
