// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.Question;

/************************************************************/
/**
 * 
 */
public class Matching extends Question {
	/**
	 * 
	 */
	private ArrayList<CorrectResponse> responsesLeftUser;
	/**
	 * 
	 */
	private ArrayList<CorrectResponse> responsesRight;
	/**
	 * 
	 */
	private int numUserResponses;
	/**
	 * 
	 */
	private ArrayList<CorrectResponse> responsesLeftSystem;

	/**
	 * 
	 */
	public void Matching() {
	}

	/**
	 * 
	 * @param index1 
	 * @param index2 
	 * @return 
	 */
	public void swapResponses(int index1, int index2) {
	}

	/**
	 * 
	 * @param responses 
	 * @return 
	 */
	public void setResponsesLeftUser(ArrayList<CorrectResponse> responses) {
	}

	/**
	 * 
	 * @return 
	 */
	public ArrayList<CorrectResponse> getResponsesLeftUser() {
	}

	/**
	 * 
	 * @param responses 
	 * @return 
	 */
	public void setResponsesRight(ArrayList<CorrectResponse> responses) {
	}

	/**
	 * 
	 * @return 
	 */
	public ArrayList<CorrectResponse> getResponsesRight() {
	}

	/**
	 * 
	 * @param responses 
	 * @return 
	 */
	public void setResponsesLeftSystem(ArrayList<CorrectResponse> responses) {
	}

	/**
	 * 
	 * @return 
	 */
	public ArrayList<CorrectResponse> getResponsesLeftSystem() {
	}
};
