// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import java.util.*;
import SurveyApp.Question;

/************************************************************/
/**
 * 
 */
public class Matching extends Question {
	/**
	 * 
	 */
	private ArrayList<CorrectResponse> responsesLeftUser;
	/**
	 * 
	 */
	private ArrayList<CorrectResponse> responsesRight;
	/**
	 * 
	 */
	private int numUserResponses;
	/**
	 * 
	 */
	private ArrayList<CorrectResponse> responsesLeftSystem;

	/**
	 * 
	 */
	public Matching() {
	}
	
	public Matching(ArrayList<CorrectResponse> responsesLeftSystem, 
			ArrayList<CorrectResponse> responsesRight) {
		this.responsesLeftSystem = responsesLeftSystem;
		this.responsesRight = responsesRight;
		this.numUserResponses = responsesRight.size();
	}

	/**
	 * 
	 * @param index1 
	 * @param index2 
	 * @return 
	 */
	public void swapResponsesLeftUser(int index1, int index2) {
		Collections.swap(this.responsesLeftUser, index1, index2);
	}

	/**
	 * 
	 * @param responses 
	 * @return 
	 */
	public void setResponsesLeftUser(ArrayList<CorrectResponse> responses) {
		this.responsesLeftUser = responses;
	}

	/**
	 * 
	 * @return 
	 */
	public ArrayList<CorrectResponse> getResponsesLeftUser() {
		return this.responsesLeftUser;
	}

	/**
	 * 
	 * @param responses 
	 * @return 
	 */
	public void setResponsesRight(ArrayList<CorrectResponse> responses) {
		this.responsesRight = responses;
		this.numUserResponses = responses.size();
	}

	/**
	 * 
	 * @return 
	 */
	public ArrayList<CorrectResponse> getResponsesRight() {
		return this.responsesRight;
	}

	/**
	 * 
	 * @param responses 
	 * @return 
	 */
	public void setResponsesLeftSystem(ArrayList<CorrectResponse> responses) {
		this.responsesLeftSystem = responses;
	}

	/**
	 * 
	 * @return 
	 */
	public ArrayList<CorrectResponse> getResponsesLeftSystem() {
		return this.responsesLeftSystem;
	}

	public int getNumUserResponses() {
		return numUserResponses;
	}
};
