// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.Menu;

/************************************************************/
/**
 * 
 */
public class MenuSave extends Menu {
    /**
     * 
     */
    private String author;
    /**
     * 
     */
    private String title;
    /**
     * 
     */
    private String filePath;

    /**
     * 
     */
    public void MenuSave() {
    }

    /**
     * 
     * @param filePath
     * @return
     */
    public void save(String filePath) {
    }
};
