// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import java.util.*;

/************************************************************/
/**
 * 
 */
public class MenuManager {
	/**
	 * 
	 */
	private ArrayList<Menu> menus;

	/**
	 * 
	 */
	public MenuManager() {
	}

	/**
	 * 
	 * @param menus 
	 * @return 
	 */
	public void setMenus(ArrayList<Menu> menus) {
	}

	/**
	 * 
	 * @param index 
	 * @return 
	 */
	public void displayMenu(int index) {
	}
};
