// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.Menu;

/************************************************************/
/**
 * 
 */
public class MenuEdit extends Menu {
	/**
	 * 
	 */
	private String filePath;
	/**
	 * 
	 */
	private String author;
	/**
	 * 
	 */
	private String title;

	/**
	 * 
	 * @param filePath 
	 */
	public void load(String filePath) {
	}
};
