// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import java.util.*;
import SurveyApp.Menu;
import SurveyApp.MenuChoice;

/************************************************************/
/**
 * 
 */
public class MenuHome extends Menu {

	public MenuHome() {
		MenuChoice choice1 = new MenuChoice("Create", 1);
		MenuChoice choice2 = new MenuChoice("Edit", 2);
		MenuChoice choice3 = new MenuChoice("Fill", 3);
		MenuChoice choice4 = new MenuChoice("Grade", 4);
		MenuChoice choice5 = new MenuChoice("Exit", 5);
		
		ArrayList<MenuChoice> choices = new ArrayList<MenuChoice>();
		
		choices.add(choice1);
		choices.add(choice2);
		choices.add(choice3);
		choices.add(choice4);
		choices.add(choice5);
		
		this.setChoices(choices);
	}
	
	/*
	 * @override
	 */
	
	public SurveyApp.Menu selectChoice(int index) {
		
		Menu newMenu;
		
		switch (index) {
		case 1:
			/* Create */
			newMenu = new MenuCreate();
		case 2:
			/* Edit */
			newMenu = new MenuEdit();
		case 3:
			/* Fill */
			newMenu = new MenuFill();
		case 4:
			/* Grade */
			newMenu = new MenuGrade();
		case 5:
			/* Exit */
			newMenu = null;
			System.exit(0);
			
		default:
			newMenu = null;
			System.err.println("selectChoice(): invalid index");
		}
		
		return newMenu;
	}
};
