// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import java.util.*;

/************************************************************/
/**
 * 
 */
public abstract class Menu {
	/**
	 * 
	 */
	private ArrayList<MenuChoice> choices;
	/**
	 * 
	 */
	private int numberChoices;

	/**
	 * 
	 */
	public Menu() {
	}

	public Menu(ArrayList<MenuChoice> choices) {
		this.choices = choices;
	}
	
	/**
	 * 
	 * @return 
	 * @param output 
	 */
	public void display(Output output) {
	}

	/**
	 * 
	 * @param index 
	 * @return 
	 */
	public SurveyApp.Menu selectChoice(int index) {
		/* Overridden by child classes */
		return null;
	}

	/**
	 * 
	 * @return 
	 */
	public ArrayList<MenuChoice> getChoices() {
		return this.choices;
	}

	/**
	 * 
	 * @param choices 
	 * @return 
	 */
	public void setChoices(ArrayList<MenuChoice> choices) {
		this.choices = choices;
	}

	/**
	 * 
	 * @return 
	 */
	public int getNumberChoices() {
		this.numberChoices = this.choices.size();
		return this.numberChoices;
	}
};
