// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.Menu;

/************************************************************/
/**
 * 
 */
public class MenuAddQuestion extends Menu {
    /**
     * 
     */
    private String question;

    /**
     * 
     */
    public void MenuAddQuestion() {
    }
};
