// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import java.util.*;

/************************************************************/
/**
 * 
 */
public abstract class Menu {
	/**
	 * 
	 */
	private ArrayList<MenuChoice> choices;
	/**
	 * 
	 */
	private int numberChoices;

	/**
	 * 
	 */
	public Menu() {
	}

	public Menu(ArrayList<MenuChoice> choices) {
		this.choices = choices;
		this.numberChoices = choices.size();
	}
	
	/**
	 * 
	 * @return 
	 * @param output 
	 */
	public void display(Output output) {
	}

	/**
	 * 
	 * @param index 
	 * @return 
	 */
	public SurveyApp.Menu selectChoice(int index) {
		/* Overridden by child classes */
		return null;
	}

	/**
	 * 
	 * @return 
	 */
	public ArrayList<MenuChoice> getChoices() {
		return this.choices;
	}

	/**
	 * 
	 * @param choices 
	 * @return 
	 */
	public void setChoices(ArrayList<MenuChoice> choices) {
		this.choices = choices;
		this.numberChoices = choices.size();
	}

	/**
	 * 
	 * @return 
	 */
	public int getNumberChoices() {
		return this.numberChoices;
	}
	
	public String toString() {
		String out = "";
		
		for (int i = 0; i < this.getNumberChoices(); i++) {
			MenuChoice thisChoice = this.getChoices().get(i);
			out += thisChoice.getIndex() + ") " + thisChoice.getValue() + "\n";
		}
		
		return out;
	}
};
