// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.Menu;

/************************************************************/
/**
 * 
 */
public class MenuCreate extends Menu {
	/**
	 * 
	 */
	private String filePath;
	/**
	 * 
	 */
	private String author;
	/**
	 * 
	 */
	private String title;

	/**
	 * 
	 */
	public void MenuCreate() {
	}

	/**
	 * 
	 * @return 
	 */
	public void save() {
	}

	/**
	 * 
	 * @return 
	 */
	public void quit() {
	}
};
