// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import java.util.ArrayList;
import java.util.Scanner;
//import java.util.regex.Pattern;
//import java.io.*;

import SurveyApp.Menu;
import SurveyApp.Survey;
//import SurveyApp.Test;
import SurveyApp.SurveyManager;

/************************************************************/

public class MenuCreateSurvey extends Menu {

    private String filePath;
    private static SurveyManager surveyManager;
    private Survey survey;
    private ArrayList<Question> questions;
    private Boolean isGradable;
    private Boolean isSaved;

    private Scanner reader = new Scanner(System.in);

    public MenuCreateSurvey() {
	MenuChoice choice1 = new MenuChoice("Add a new T/F question", 1);
	MenuChoice choice2 = new MenuChoice("Add a new multiple choice question", 2);
	MenuChoice choice3 = new MenuChoice("Add a new short answer question", 3);
	MenuChoice choice4 = new MenuChoice("Add a new essay question", 4);
	MenuChoice choice5 = new MenuChoice("Add a new ranking question", 5);
	MenuChoice choice6 = new MenuChoice("Add a new matching question", 6);
	MenuChoice choice7 = new MenuChoice("Return", 7);

	ArrayList<MenuChoice> choices = new ArrayList<MenuChoice>();

	choices.add(choice1);
	choices.add(choice2);
	choices.add(choice3);
	choices.add(choice4);
	choices.add(choice5);
	choices.add(choice6);
	choices.add(choice7);

	this.setChoices(choices);

	surveyManager = SurveyManager.getInstance();
	this.survey = new Survey();
	surveyManager.setSurveyActive(this.survey);
	surveyManager.setSurveyActiveGradable(false);
	this.questions = new ArrayList<Question>();
	this.isSaved = false;
    }

    protected int promptForInteger(String prompt) {
	System.out.println(prompt);
	int result = 0;

	/* Catch any invalid (non-integer) input and request valid input */
	while (result == 0) {
	    try {
		result = Integer.parseInt(this.reader.nextLine());
	    } catch (NumberFormatException e) {
		// e.printStackTrace();
		System.out.println("Please enter an integer");
	    }
	}

	return result;
    }

    protected String promptForString(String prompt) {
	System.out.println(prompt);
	String result = this.reader.nextLine();

	return result;
    }

    /*
     * Prompts for n correct responses, one at a time, then returns a new list
     * containing those responses, in order.
     */
    private ArrayList<CorrectResponse> promptForCorrectResponses(int n) {

	String userResponse;
	CorrectResponse newResponse;
	ArrayList<CorrectResponse> newResponses = new ArrayList<CorrectResponse>();

	for (int i = 0; i < n; i++) {
	    userResponse = this.promptForString("Enter Choice #" + (i + 1) + ":");
	    newResponse = new CorrectResponseString(userResponse);
	    newResponses.add(newResponse);
	}

	return newResponses;
    }

    public Menu selectChoice(int index) {
	Menu newMenu;
	String userResponse1 = "";
	Question newQuestion;
	Prompt newPrompt;
	CorrectResponse newResponse;
	ArrayList<CorrectResponse> newResponses;
	int numberNewResponses;

	switch (index) {
	case 1:
	    /* True/False */
	    userResponse1 = this.promptForString("Enter the prompt for your true/false question:");
	    newPrompt = new PromptString(userResponse1);
	    newQuestion = new TrueFalse();
	    newQuestion.setPrompt(newPrompt);

	    this.questions.add(newQuestion);
	    surveyManager.setSaved(false);
	    newMenu = this;
	    break;
	case 2:
	    /* Multiple Choice */
	    userResponse1 = this.promptForString("Enter the prompt for your multiple choice question:");
	    newPrompt = new PromptString(userResponse1);
	    MultipleChoice newQuestionMC = new MultipleChoice();
	    newQuestionMC.setPrompt(newPrompt);

	    numberNewResponses = this
		    .promptForInteger("Enter the number of choices for your multiple choice question:");
	    newResponses = promptForCorrectResponses(numberNewResponses);
	    newQuestionMC.setResponsesPossible(newResponses);

	    this.questions.add(newQuestionMC);
	    surveyManager.setSaved(false);
	    newMenu = this;
	    break;
	case 3:
	    /* Short answer */
	    userResponse1 = this.promptForString("Enter the prompt for your short answer question:");
	    newPrompt = new PromptString(userResponse1);
	    newQuestion = new ShortAnswer();
	    newQuestion.setPrompt(newPrompt);

	    this.questions.add(newQuestion);
	    surveyManager.setSaved(false);
	    newMenu = this;
	    break;
	case 4:
	    /* Essay */
	    userResponse1 = this.promptForString("Enter the prompt for your essay question:");
	    newPrompt = new PromptString(userResponse1);
	    newQuestion = new Essay();
	    newQuestion.setPrompt(newPrompt);

	    this.questions.add(newQuestion);
	    surveyManager.setSaved(false);
	    newMenu = this;
	    break;
	case 5:
	    /* Ranking */
	    userResponse1 = this.promptForString("Enter the prompt for your ranking question:");
	    newPrompt = new PromptString(userResponse1);
	    Ranking newQuestionR = new Ranking();
	    newQuestionR.setPrompt(newPrompt);

	    numberNewResponses = this.promptForInteger("Enter the number of choices for your ranking question:");
	    newResponses = promptForCorrectResponses(numberNewResponses);
	    newQuestionR.setResponsesLeftSystem(newResponses);

	    this.questions.add(newQuestionR);
	    surveyManager.setSaved(false);
	    newMenu = this;
	    break;
	case 6:
	    /* Matching */
	    userResponse1 = this.promptForString("Enter the prompt for your matching question:");
	    newPrompt = new PromptString(userResponse1);
	    Matching newQuestionM = new Matching();
	    newQuestionM.setPrompt(newPrompt);

	    numberNewResponses = this.promptForInteger("Enter the number of choices for your matching question:");
	    
	    /* Get/set left choices. */
	    newResponses = new ArrayList<CorrectResponse>();

	    for (int i = 0; i < numberNewResponses; i++) {
		userResponse1 = this.promptForString("Enter Left Choice #" + (i + 1) + ":");
		newResponse = new CorrectResponseString(userResponse1);
		newResponses.add(newResponse);
	    }

	    newQuestionM.setResponsesLeftSystem(newResponses);
	    
	    /* Get/set right choices */
	    newResponses = new ArrayList<CorrectResponse>();

	    for (int i = 0; i < numberNewResponses; i++) {
		userResponse1 = this.promptForString("Enter Right Choice #" + (i + 1) + ":");
		newResponse = new CorrectResponseString(userResponse1);
		newResponses.add(newResponse);
	    }

	    newQuestionM.setResponsesRight(newResponses);

	    this.questions.add(newQuestionM);
	    surveyManager.setSaved(false);
	    newMenu = this;
	    break;
	case 7:
	    /* Return to home menu */
	    newMenu = new MenuHome();
	    break;

	default:
	    newMenu = null;
	}

	this.survey.setQuestions(this.questions);

	return newMenu;
    }
    
    public String toString() {
	String out = DIVIDER + "\n\t\t\t || Survey Creation Menu ||\n" + DIVIDER + "\n";

	if (!this.getSurvey().getQuestions().isEmpty()) {
	    out += "\nCurrent survey: \n" + this.survey + "\n" + DIVIDER + "\n";
	}

	for (int i = 0; i < this.getNumberChoices(); i++) {
	    MenuChoice thisChoice = this.getChoices().get(i);
	    out += thisChoice.getIndex() + ") " + thisChoice.getValue() + "\n";
	}

	return out;
    }

    public String getFilePath() {
	return filePath;
    }

    public void setFilePath(String filePath) {
	this.filePath = filePath;
    }

    public Survey getSurvey() {
	return survey;
    }

    public void setSurvey(Survey survey) {
	this.survey = survey;
    }

    public Boolean getIsGradable() {
	return isGradable;
    }

    public void setIsGradable(Boolean isGradable) {
	this.isGradable = isGradable;
    }

    public Boolean getIsSaved() {
	return isSaved;
    }

    public void setIsSaved(Boolean isSaved) {
	this.isSaved = isSaved;
    }

};
