// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import java.util.*;
import SurveyApp.Question;

/************************************************************/
/**
 * 
 */
public class MultipleChoice extends Question implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = -6288619557660521299L;
    /**
     * 
     */
    private int numberChoices;
    /**
     * 
     */
    private ArrayList<CorrectResponse> responsesSystem;

    private ArrayList<CorrectResponse> responsesPossible;

    /**
     * 
     */
    public MultipleChoice() {
    }

    /**
     * 
     * @return
     * @param responses
     */
    public void setResponsesSystem(ArrayList<CorrectResponse> responses) {
	this.responsesSystem = responses;
    }

    public ArrayList<CorrectResponse> getResponsesSystem() {
	return this.responsesSystem;
    }

    public int getNumberChoices() {
	return numberChoices;
    }

    public boolean isCorrect() {
	boolean result = true;

	/* Check that each system response is contained in the user responses */
	for (int i = 0; i < this.getResponsesSystem().size(); i++) {
	    if (!this.getResponsesUser().contains(this.getResponsesSystem().get(i))) {
		result = false;
	    }
	}

	/* Check that each user response is contained in the system responses */
	for (int i = 0; i < this.getResponsesUser().size(); i++) {
	    if (!this.getResponsesSystem().contains(this.getResponsesUser().get(i))) {
		result = false;
	    }
	}

	return result;
    }

    public ArrayList<CorrectResponse> getResponsesPossible() {
	return responsesPossible;
    }

    public void setResponsesPossible(ArrayList<CorrectResponse> responsesPossible) {
	this.responsesPossible = responsesPossible;
    }

    public String toString() {
	String currentAnswer;

	if (this.getResponsesUser().isEmpty()) {
	    currentAnswer = "";
	} else {
	    currentAnswer = this.getResponsesUser().get(0).toString();
	}

	String str = "[Multiple Choice]\t" + this.getPrompt() + " : " + currentAnswer;

	str += "\n\t(Possible answers) " + this.getResponsesPossible();

	if (this.responsesSystem != null) {
	    str += "\n\t(Correct answers) " + this.getResponsesSystem();
	}

	return str;
    }

};
