// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import java.util.*;
import SurveyApp.Question;

/************************************************************/
/**
 * 
 */
public class MultipleChoice extends Question {
	/**
	 * 
	 */
	private int numberChoices;
	/**
	 * 
	 */
	private ArrayList<CorrectResponse> responsesSystem;

	/**
	 * 
	 */
	public MultipleChoice() {
	}

	/**
	 * 
	 * @return 
	 * @param responses 
	 */
	public void setResponsesSystem(ArrayList<CorrectResponse> responses) {
	}

	/**
	 * 
	 * @return 
	 */
	public ArrayList<CorrectResponse> getResponsesSystem() {
		return this.responsesSystem;
	}

	public int getNumberChoices() {
		return numberChoices;
	}
};
