// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import java.util.*;
import SurveyApp.Question;

/************************************************************/
/**
 * 
 */
public class MultipleChoice extends Question {
	/**
	 * 
	 */
	private int numberChoices;
	/**
	 * 
	 */
	private ArrayList<CorrectResponse> responsesSystem;

	/**
	 * 
	 */
	public MultipleChoice() {
	}

	/**
	 * 
	 * @return 
	 * @param responses 
	 */
	public void setResponsesSystem(ArrayList<CorrectResponse> responses) {
		this.responsesSystem = responses;
	}

	/**
	 * 
	 * @return 
	 */
	public ArrayList<CorrectResponse> getResponsesSystem() {
		return this.responsesSystem;
	}

	public int getNumberChoices() {
		return numberChoices;
	}
	
	public boolean isCorrect() {
		boolean result = true;
		
		/* Check that each system response is contained in the user responses */
		for (int i = 0; i < this.getResponsesSystem().size(); i++) {
			if (!this.getResponsesUser().contains(this.getResponsesSystem().get(i))) {
				result = false;
			}
		}
		
		/* Check that each user response is contained in the system responses */
		for (int i = 0; i < this.getResponsesUser().size(); i++) {
			if (!this.getResponsesSystem().contains(this.getResponsesUser().get(i))) {
				result = false;
			}
		}
		
		return result;
	}
};
