// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.Output;

/************************************************************/
/**
 * 
 */
public class OutputTerminal extends Output {
	/**
	 * 
	 * @param output 
	 * @return 
	 */
	public void display(int output) {
	}

	/**
	 * 
	 * @param output 
	 * @return 
	 */
	public void display(String output) {
	}

	/**
	 * 
	 */
	public void OutputTerminal() {
	}
};
