// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.Output;

/************************************************************/
/**
 * 
 */
public abstract class Prompt {
	/**
	 * 
	 * @return 
	 * @param output 
	 */
	public void display(Output output) {
	}
	
	public String toString() {
		return new String("");
	}
};
