// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.Prompt;
import SurveyApp.Output;

/************************************************************/
/**
 * 
 */
public class PromptString extends Prompt {
	/**
	 * 
	 */
	private String prompt;
	
	public PromptString() {
		
	}
	
	public PromptString(String prompt) {
		this.prompt = prompt;
	}
	
	public void display(Output output) {
		output.displayString(this.prompt);
	}
	
	public String toString() {
		return this.prompt;
	}

	public String getPrompt() {
		return this.prompt;
	}

	public void setPrompt(String prompt) {
		this.prompt = prompt;
	}
};
