// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import java.util.*;
import SurveyApp.Essay;

/************************************************************/
/**
 * 
 */
public class ShortAnswer extends Essay {
	/**
	 * 
	 */
	private int maxLength;
	/**
	 * 
	 */
	private ArrayList<CorrectResponse> responsesSystem;

	/**
	 * 
	 */
	public ShortAnswer() {
	}

	/**
	 * 
	 * @param length 
	 * @return 
	 */
	public void setMaxLength(int length) {
		this.maxLength = length;
	}

	/**
	 * 
	 * @return 
	 */
	public int getMaxLength() {
		return this.maxLength;
	}

	/**
	 * 
	 * @return 
	 */
	public ArrayList<CorrectResponse> getResponsesSystem() {
		return this.responsesSystem;
	}

	/**
	 * 
	 * @return 
	 * @param responses 
	 */
	public void setResponsesSystem(ArrayList<CorrectResponse> responses) {
		if (responses.size() > 1) {
			System.err.println("setResponsesSystem(): Error, more than one response provided");
		}
		
		this.responsesSystem = responses;
	}
};
