// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.Survey;

/************************************************************/
/**
 * 
 */
public class SurveyManager {
	/**
	 * 
	 */
	private String filePath;

	/**
	 * 
	 * @param filePath 
	 */
	public SurveyManager() {
	}

	/**
	 * 
	 * @param filePath 
	 */
	public void load(String filePath) {
	}

	/**
	 * 
	 * @param survey 
	 * @param filePath 
	 */
	public void save(Survey survey, String filePath) {
	}

	/**
	 * 
	 * @return 
	 */
	public void enumerate() {
	}
};
