// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.MultipleChoice;
import SurveyApp.Output;

/************************************************************/
/**
 * 
 */
public class TrueFalse extends MultipleChoice {

	public TrueFalse() {
	}
	
	public void display(Output output) {
		String line = "[T/F]\t" + this.getPrompt().toString();
		
		output.displayString(line);
	}
	
	public String toString() {
		String currentAnswer;
		
		if (this.getResponsesUser().isEmpty()) {
			currentAnswer = "";
		} else {
			currentAnswer = this.getResponsesUser().get(0).toString();
		}
		
		String line = "[T/F]\t" + this.getPrompt().toString() + " : "
				+ currentAnswer;
		
		return line;
	}
};
