// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.MultipleChoice;

/************************************************************/
/**
 * 
 */
public class TrueFalse extends MultipleChoice {

	public TrueFalse() {
	}
	

};
