// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.CorrectResponse;

/************************************************************/
/**
 * 
 */
public class CorrectResponseInteger extends CorrectResponse {
	/**
	 * 
	 */
	private int response;

	/**
	 * 
	 */
	public void CorrectResponseInteger() {
	}

	/**
	 * 
	 * @return 
	 */
	public String getResponse() {
	}

	/**
	 * 
	 * @param other 
	 * @return 
	 */
	public int compareTo(CorrectResponse other) {
	}

	/**
	 * 
	 * @param response 
	 * @return 
	 */
	public void setResponse(String response) {
	}
};
