// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.Comparable;
import SurveyApp.Output;
import SurveyApp.Serializable;

/************************************************************/
/**
 * 
 */
public abstract class CorrectResponse {
	/**
	 * 
	 */
	public void CorrectResponse() {
	}

	/**
	 * 
	 * @param other 
	 * @return 
	 */
	public void compareTo(SurveyApp.CorrectResponse other) {
	}

	/**
	 * 
	 * @param output 
	 * @return 
	 */
	public void display(Output output) {
	}
};
