// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.CorrectResponse;

/************************************************************/
/**
 * 
 */
public class CorrectResponseBoolean extends CorrectResponse {
	/**
	 * 
	 */
	public boolean response;

	/**
	 * 
	 * @param response 
	 * @return 
	 */
	public void setResponse(boolean response) {
	}

	/**
	 * 
	 */
	public void CorrectResponseBoolean() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean getResponse() {
	}

	/**
	 * 
	 * @param other 
	 * @return 
	 */
	public int compareTo(CorrectResponse other) {
	}
};
