// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.Menu;
import SurveyApp.Output;

/************************************************************/
/**
 * 
 */
public class MenuPrompt extends Menu {
	/**
	 * 
	 */
	private String title;
	/**
	 * 
	 */
	private String author;
	/**
	 * 
	 */
	private String filePath;

	/**
	 * 
	 */
	public void MenuPrompt() {
	}

	/**
	 * 
	 * @param filePath 
	 * @return 
	 */
	public void load(String filePath) {
	}

	/**
	 * 
	 * @return 
	 * @param output 
	 */
	public void display(Output output) {
	}
};
