// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.MultipleChoice;

/************************************************************/
/**
 * 
 */
public class TureFalse extends MultipleChoice {
	/**
	 * 
	 */
	private int numberChoices = 2;
	/**
	 * 
	 */
	private int numberResponsesUser = 1;

	/**
	 * 
	 */
	public void TrueFalse() {
	}
};
