// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.Question;

/************************************************************/
/**
 * 
 */
public class Essay extends Question {
	/**
	 * 
	 */
	private int numberResponses = 1;

	/**
	 * 
	 */
	public void Essay() {
	}
};
