// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.Menu;

/************************************************************/
/**
 * 
 */
public class MenuFill extends Menu {
	/**
	 * 
	 */
	public void MenuFill() {
	}
};
