// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.Prompt;

/************************************************************/
/**
 * 
 */
public class PromptString extends Prompt {
	/**
	 * 
	 */
	private String prompt;
};
