// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.CorrectResponse;
import SurveyApp.Output;
import SurveyApp.Prompt;
import SurveyApp.Serializable;

/************************************************************/
/**
 * 
 */
public abstract class Question {
	/**
	 * 
	 */
	private Prompt prompt;
	/**
	 * 
	 */
	private ArrayList<CorrectResponse> responsesUser;
	/**
	 * 
	 */
	private int numberResponses = 1;

	/**
	 * 
	 */
	public void Question() {
	}

	/**
	 * 
	 * @return 
	 * @param prompt 
	 */
	public void setPrompt(Prompt prompt) {
	}

	/**
	 * 
	 * @return 
	 */
	public Prompt getPrompt() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getNumberResponsesUser() {
	}

	/**
	 * 
	 * @return 
	 * @param index 
	 * @param response 
	 */
	public void setResponseUser(int index, CorrectResponse response) {
	}

	/**
	 * 
	 * @return 
	 * @param index 
	 */
	public CorrectResponse getResponseUser(int index) {
	}

	/**
	 * 
	 * @return 
	 * @param responses 
	 */
	public void setResponsesUser(ArrayList<CorrectResponse> responses) {
	}

	/**
	 * 
	 * @return 
	 */
	public ArrayList<CorrectResponse> getResponsesUser() {
	}

	/**
	 * 
	 * @return 
	 * @param output 
	 */
	public void display(Output output) {
	}
};
