// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.Matching;

/************************************************************/
/**
 * 
 */
public class Ranking extends Matching {
	/**
	 * 
	 */
	public void Ranking() {
	}
};
