// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.Essay;

/************************************************************/
/**
 * 
 */
public class ShortAnswer extends Essay {
	/**
	 * 
	 */
	private int maxLength;
	/**
	 * 
	 */
	private ArrayList<CorrectResponse> responsesSystem;

	/**
	 * 
	 */
	public void ShortAnswer() {
	}

	/**
	 * 
	 * @param length 
	 * @return 
	 */
	public void setMaxLength(int length) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getMaxLength() {
	}

	/**
	 * 
	 * @return 
	 */
	public ArrayList<CorrectResponse> getResponsesSystem() {
	}

	/**
	 * 
	 * @return 
	 * @param responses 
	 */
	public void setResponsesSystem(ArrayList<CorrectResponse> responses) {
	}
};
