// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.Output;
import SurveyApp.Question;
import SurveyApp.Serializable;

/************************************************************/
/**
 * 
 */
public class Survey {
	/**
	 * 
	 */
	private String author;
	/**
	 * 
	 */
	private String title;
	/**
	 * 
	 */
	private ArrayList<Question> questions;
	/**
	 * 
	 */
	private int numberQuestions;
	/**
	 * 
	 */
	private Output output;

	/**
	 * 
	 * @param author 
	 * @param title 
	 * @param questions 
	 */
	public void Survey(String author, String title, ArrayList<Question> questions) {
	}

	/**
	 * 
	 * @return 
	 */
	public void addQuestion() {
	}

	/**
	 * 
	 * @return 
	 * @param index 
	 */
	public void editQuestion(int index) {
	}

	/**
	 * 
	 * @param index 
	 * @return 
	 */
	public void removeQuestion(int index) {
	}

	/**
	 * 
	 * @return 
	 * @param index 
	 */
	public Question getQuestion(int index) {
	}

	/**
	 * 
	 * @return 
	 * @param output 
	 */
	public void display(Output output) {
	}

	/**
	 * 
	 * @return 
	 */
	public void fill() {
	}

	/**
	 * 
	 * @return 
	 */
	public void tabulate() {
	}
};
