// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SurveyApp;

import SurveyApp.CorrectResponse;
import SurveyApp.Survey;

/************************************************************/
/**
 * 
 */
public class Test extends Survey {
	/**
	 * 
	 */
	private int grade;
	/**
	 * 
	 */
	private ArrayList<CorrectResponse> correctAnswers;

	/**
	 * 
	 */
	public void Test() {
	}

	/**
	 * 
	 * @param index 
	 * @param answer 
	 * @return 
	 */
	public void addCorrectAnswer(int index, CorrectResponse answer) {
	}

	/**
	 * 
	 * @param answer 
	 * @return 
	 */
	public void enterAnswer(CorrectResponse answer) {
	}

	/**
	 * 
	 * @param answers 
	 * @return 
	 */
	public void enterAnswers(ArrayList<CorrectResponse> answers) {
	}

	/**
	 * 
	 * @param index 
	 * @param answer 
	 * @return 
	 */
	public void editAnswer(int index, CorrectResponse answer) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getGrade() {
	}

	/**
	 * 
	 * @param index 
	 * @return 
	 */
	public boolean checkAnswer(int index) {
	}

	/**
	 * 
	 * @return 
	 */
	public ArrayList<Boolean> checkAnswers() {
	}

	/**
	 * 
	 * @return 
	 */
	public void displayAnswers() {
	}
};
